<?php return [
	"AdsBot-Google-Mobile",
    "AhrefsSiteAudit",
	"APIs-Google",
	"Applebot",
	"archive.org_bot",
	"Baiduspider",
	"bingbot",
	"BingPreview",
	"bitlybot",
	"Digg Deeper",
	"Discordbot",
	"DuckDuckBot",
	"DuckDuckGo-Favicons-Bot",
	"Embedly",
	"facebookexternalhit",
	"Facebot",
	"Feedfetcher-Google",
	"Feedly",
	"FlipboardProxy",
	"Google Favicon",
	"Google Web Preview",
	"Google-Adwords-Instant",
	"Google-Site-Verification",
	"Google-Structured-Data-Testing-Tool",
	"Googlebot-Image",
	"Googlebot-Mobile",
	"Googlebot-News",
	"Googlebot-Video",
	"Googlebot",
	"ia_archiver", // Alexa"
	"Iframely",
	"LinkedInBot",
	"Mail.RU_Bot",
	"Mastodon",
	"Mediapartners \(Googlebot\)",
	"Mediapartners-Google",
	"msnbot",
	"pinterest.com.bot",
	"PocketParser",
	"redditbot",
	"SkypeUriPreview",
	"Slack-ImgProxy",
	"Slackbot",
	"Slurp",
	"TelegramBot",
	"Twitterbot",
	"vkShare",
	"web-archive-net.com.bot",
	"WhatsApp",
	"Yahoo Link Preview",
	"YandexAccessibilityBot",
	"YandexBot",
	"YandexMobileBot",
	//"Mozilla" // for test
];